version: '3.7'
services:
  app:
    ports:
      - 8080:8080
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - WEATHER_API_KEY=
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M