version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  migration:
    image: migrate/migrate
    container_name: migration
    depends_on:
      mysql: 
        condition: service_healthy
    command: [ "-path", "/migrations/", "-database", "mysql://root:root@tcp(mysql:3306)/orders", "up"]
    volumes:
      - ./migrations:/migrations
    
