version: '3.7'
services:
  app:
    ports:
      - 8080:8080
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_PORT=8080
      - SERVICE_B_URL=http://service_b:8081/cep/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M