version: '3.7'
services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    hostname: app
    ports:
      - 8080:8080
    environment:
      - WEB_SERVER_PORT=8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - REDIS_RATE_LIMIT_TTL=10
      - REQUEST_BLOCKING_TIME_IP=60
      - REQUEST_BLOCKING_TIME_TOKEN=60
      - MAX_REQUESTS_PER_IP_PER_SECOND=10
      - MAX_REQUESTS_PER_TOKEN_PER_SECOND=100
      - RATE_LIMITER_IP_ENABLED=true
      - RATE_LIMITER_TOKEN_ENABLED=true
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
  k6:
    image: grafana/k6
    volumes:
      - ./test:/test
    command: run /test/load-test.js
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M